In [5]:
import pandas as pd
import numpy as np

In [53]:
dataset = pd.read_csv("MarksDataset.csv")
df = dataset.copy()
df

name  hrs  marks
0   manish    4     40
1  deepika    6     60
2  likhith    8     80
3  Karthik    3     30

In [14]:
x = df["hrs"]
x

0    4
1    6
2    8
3    3
Name: hrs, dtype: int64

In [15]:
y = df["marks"]
y

0    40
1    60
2    80
3    30
Name: marks, dtype: int64

In [16]:
# y is change through x by 10 
# y = 10 * x -> 10 is coefficient
# the above function is a model, once a function created we can say that model is created.

In [18]:
# the above function is obtained by linear regression function provided by python - scikitlearn library

In [25]:
from sklearn.linear_model import LinearRegression

In [27]:
# it tells the python that iam gng to give a mathematical linear algebra formula i.e, y = cx

model = LinearRegression()

In [32]:
# the goal of the fit function is to find the value of c based on the data which we given in arguements
model.fit(x, y)

ValueError: Expected 2D array, got 1D array instead:
array=[4 6 8 3].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [42]:
# since model.fit() function accepts 2d array so reshaping the x values
X = x.values.reshape(4,1)
X

array([[4],
       [6],
       [8],
       [3]])

In [43]:
# training the model
model.fit(X,y)

LinearRegression()

In [45]:
model.predict(5)

ValueError: Expected 2D array, got scalar array instead:
array=5.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [47]:
# X is in 2d it expects the arguement to also be 2d in predict function
# The goal of the function is it multiplies each arguement with the c values calculated above
model.predict([[5],[6],[10]])

array([ 50.,  60., 100.])

In [49]:
# c value
model.coef_

array([10.])

In [51]:
# to save the above model we have a library called joblib
import joblib
help(joblib.dump)

Help on function dump in module joblib.numpy_pickle:

dump(value, filename, compress=0, protocol=None, cache_size=None)
    Persist an arbitrary Python object into one file.
    
    Read more in the :ref:`User Guide <persistence>`.
    
    Parameters
    -----------
    value: any Python object
        The object to store to disk.
    filename: str, pathlib.Path, or file object.
        The file object or path of the file in which it is to be stored.
        The compression method corresponding to one of the supported filename
        extensions ('.z', '.gz', '.bz2', '.xz' or '.lzma') will be used
        automatically.
    compress: int from 0 to 9 or bool or 2-tuple, optional
        Optional compression level for the data. 0 or False is no compression.
        Higher value means more compression, but also slower read and
        write times. Using a value of 3 is often a good compromise.
        See the notes for more details.
        If compress is True, the compression level use

In [52]:
joblib.dump(model,"myMarks.model")

['myMarks.model']